config/routes.rb
MagSys::Application.routes.draw do
  root 'main#index'
  get 'admin' , :to => "access#index"

  resources :main

  resources :orders 

  resources :contracts do
      collection do
      put :add
    end
  end

  resources :messages, :except => [:edit]

  resources :invoices

  resources :payments, :only => [:show, :index, :new, :create, :destroy]

  resources :users do
        collection do
        put :add
      end
  end

  resources :agencies

  resources :clients

  resources :magazines do
    resources :issues do 
      resources :fields do
        
      end

    end
  end

match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

	has_many :payments
	belongs_to :contract


	   validates :total, :presence => true,
                   :numericality => { :greater_than_or_equal_to => 0 }
  	# validates :remaining, :presence => true,
  	# 				       numericality: true
  	validates :date, 	:presence => true
  	validates :due_date, 	:presence => true
    validates_date :due_date, :after => :date
  	validates :contract_id, :presence => true,
  							numericality: true					
  	validates_length_of  :note, :maximum => 500		
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :confirm_logged_in
  before_action :is_power_login, except: [:index, :show]
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :set_contracts, only: [:new, :create, :edit, :update]
  
  # GET /invoices
  # GET /invoices.json
  def index
    if is_power
      @invoices = Invoice.where.not(:status => 'D').paginate(:page => params[:page], :per_page => 10)
    else
      @user = User.find(session[:user_id])
      @contracts = Contract.where(:agency_id => @user.agency_id, :status => 'Y')
      @invoices = Invoice.where.not(:status => 'D').paginate(:page => params[:page], :per_page => 10).find_all_by_contract_id(@contracts)
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.remaining = @invoice.total

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.update_attribute(:status, 'D')
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:total, :remaining, :date, :due_date, :contract_id, :note, :status)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @invoice.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h4>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :status, :class => "hidden form-control", :value => 'S' %>

  <div class="form-group">
    <%= f.label :total, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <% if params[:total].nil? %>
      <%= f.number_field :total, :class => "form-control" %>
    <% else %>
      <%= f.number_field :total, :class => "form-control" , :value => params[:total] %>
    <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_field :date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :due_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_field :due_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contract_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <% if params[:contract_id].nil? %>
      <%= f.collection_select :contract_id, @contracts, :id, :id, {:prompt   => "Select contract"}, :class => "form-control" %>
    <% else %>
      <%= f.number_field :contract_id, :class => "form-control", :disabled => 'disabled', :value => params[:contract_id] %>
    <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :note, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :note, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<div class="page-header">
  <%= link_to invoices_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @invoice, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing invoice</h1>
</div>

<%= render 'form' %>

app/views/invoices/index.html.erb
<div class="page-header">
  <%if is_power %>
    <%= link_to new_invoice_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Invoice
    <% end %>
  
    <%= link_to admin_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-chevron-left"></span>
      Admin CP
    <% end %>
  <% end %>
  <h1>Listing invoices</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>            
            <th>Date</th>
            <th>Due date</th>
            <th>Total</th>
            <th>Remaining</th>
            <th>Contract number</th>
            <th>Note</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @invoices) do |invoice| %>
          <% if invoice.status == 'S' or invoice.status == 'P' and !is_power%>
            
            <td><strong><%= invoice.date %></strong></td>
            <td><strong><%= invoice.due_date %></strong></td>
            <td><strong><%= invoice.total %></strong></td>
            <td><strong><%= invoice.remaining %></strong></td>
            <td><strong><%= invoice.contract_id %></strong></td>
            <td><strong><%= invoice.note %></strong></td>
            <td><strong><%= link_to 'Pay', new_payment_path( :invoice_id => invoice.id) %></td>
          <% else %>
            
            <td><%= invoice.date %></td>
            <td><%= invoice.due_date %></td>
            <td><%= invoice.total %></td>
            <td><%= invoice.remaining %></td>
            <td><%= invoice.contract_id %></td>
            <td><%= invoice.note %></td>
            <% if is_power %>
              <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
              <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>           
          <% end %>
      <% end %>
    </tbody>
  </table>
  <center>
  <%= will_paginate @invoices, :class=> "pagination pagination-sm", renderer: BootstrapPagination::Rails %>
  </center>
</div>

app/views/invoices/new.html.erb
<div class="page-header">
  <%= link_to invoices_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New invoice</h1>
</div>

<%= render 'form' %>

app/views/invoices/show.html.erb
<div class="page-header">
  <%= link_to invoices_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_invoice_path(@invoice), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show invoice</h1>
</div>

<dl class="dl-horizontal">
  <dt>Total:</dt>
  <dd><%= @invoice.total %></dd>

  <dt>Remaining:</dt>
  <dd><%= @invoice.remaining %></dd>

  <dt>Date:</dt>
  <dd><%= @invoice.date %></dd>

  <dt>Due date:</dt>
  <dd><%= @invoice.due_date %></dd>

  <dt>Contract:</dt>
  <dd><%= @invoice.contract_id %></dd>

  <dt>Note:</dt>
  <dd><%= @invoice.note %></dd>

</dl>