config/routes.rb
MagSys::Application.routes.draw do
  root 'main#index'
  get 'admin' , :to => "access#index"

  resources :main

  resources :orders 

  resources :contracts do
      collection do
      put :add
    end
  end

  resources :messages, :except => [:edit]

  resources :invoices

  resources :payments, :only => [:show, :index, :new, :create, :destroy]

  resources :users do
        collection do
        put :add
      end
  end

  resources :agencies

  resources :clients

  resources :magazines do
    resources :issues do 
      resources :fields do
        
      end

    end
  end

match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/issue.rb
class Issue < ActiveRecord::Base

	belongs_to :magazine
	has_many :orders
	simple_roles

  def number_and_magazine_id
    @magazine = Magazine.find(magazine_id)
    number.to_s + '# ' + @magazine.title
  end

	validates :magazine_id, :presence => true,
  					  numericality: true
  	validates :number, :presence => true,
  					       :inclusion => { :in => 1..365, :message => " has to be between 1 and 365"}
  	validates :date, 	:presence => true				
  	validates :due_date, 	:presence => true
    validates_date :due_date, :before => :date
  	validates :status, :presence => true,
  					   :inclusion => { :in =>  %w(Y N) }		
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :confirm_logged_in, except: [ :index]
  before_action :is_power_login, except: [ :index, :index_other]
  before_action :find_magazine
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.where(:magazine_id => params[:magazine_id], :status => 'Y').order(:number).paginate(:page => params[:page], :per_page => 10)
    if session[:user_id]
      @user = User.find(session[:user_id])
      if is_power
        render :index
      else
        render :index_other
      end
    else
      render :index_other
    end
  end

   def index_other
     @issues = Issue.where(:magazine_id => params[:magazine_id], :status => 'Y').order(:number).paginate(:page => params[:page], :per_page => 10)
   end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to [@magazine, @issue], notice: 'Issue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @issue }
      else
        format.html { render action: 'new' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to [@magazine, @issue], notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue_count = Issue.where(:magazine_id => @issue.magazine_id).count
    if @issue_count > 1 
      @issue.update_attribute(:status, 'N')
    else
      @fields = Field.where(:magazine_id => @magazine.id)
      @fields.update_all(:status =>'N')
      @issue.update_attribute(:status, 'N')
    end
    respond_to do |format|
      format.html { redirect_to magazine_issues_url, notice: 'Issue was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:magazine_id, :number, :date, :due_date, :status)
    end

    def find_magazine
      @magazine = Magazine.find(params[:magazine_id])
    end

    
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for([@magazine, @issue], :html => { :class => "form-horizontal" }) do |f| %>
  <% if @issue.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h4>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.number_field :magazine_id, :class => "hidden form-control", :value => @magazine.id %>
  <%= f.text_field :status, :class => "hidden form-control", :value => 'Y' %>

  <div class="form-group">
    <%= f.label :magazine_title, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :magazine_title, :class => "form-control", :disabled => 'disabled', :value => @magazine.title %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :number, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :number, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_field :date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :due_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_field :due_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/issues/edit.html.erb
<div class="page-header">
  <%= link_to magazine_issues_path(@magazine), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to magazine_issue_path(@magazine, @issue), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing issue</h1>
</div>

<%= render 'form' %>

app/views/issues/index.html.erb
<div class="page-header">
  <%= link_to new_magazine_issue_path(@magazine.id), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Issue
  <% end %>
  <%= link_to magazines_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Show Magazines
  <% end %>
  <h1>Listing issues</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Magazine</th>
            <th>Number</th>
            <th>Date</th>
            <th>Due date</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @issues) do |issue| %>
            <td><%= issue.magazine.title %></td>
            <td><%= issue.number %></td>
            <td><%= issue.date %></td>
            <td><%= issue.due_date %></td>
          <td><%= link_to 'Show Fields', magazine_issue_fields_path(@magazine, issue) %></td>
        <td><%= link_to 'Edit', edit_magazine_issue_path(@magazine, issue) %></td>
        <td><%= link_to 'Destroy', magazine_issue_path(@magazine, issue), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
  <center>
  <%= will_paginate @issues, :class=> "pagination pagination-sm", renderer: BootstrapPagination::Rails %>
  </center>
</div>

app/views/issues/index_other.html.erb
<div class="page-header">
    <%= link_to main_index_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    All Magazines
  <% end %>
  <h1><%= image_tag @magazine.picture, size: "80x100", :class => 'img-rounded"'%> Listing <%= @magazine.title %> issues </h1> 
  
</div>

<% if @issues.nil? || @issues.empty? %>
  <h3> No existing issues </h3>        
<% else %>
  <div class="row">
  <%= content_tag_for(:tr, @issues) do |issue| %>
    <% if issue.status == 'Y' %>
      <div class="col-md-3 col-sm-6 ">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= Date::MONTHNAMES[issue.date.strftime("%-m").to_i]%></h3>
                <p><b>Issue number: </b><%= issue.number %></p>
                <p><b>Issue date: </b><%= issue.date %></p>
                <p><b>Template date: </b><%= issue.due_date %></p>
            <p><center>
            <%= link_to magazine_issue_fields_path(@magazine, issue), :class => 'btn btn-primary' do %>
            
            Fields
            <span class="glyphicon glyphicon-chevron-right"></span>
          <% end %></center>
        </p>
          </div>
        </div>
      </div>
    <% end %>
   <% end %> 
  </div>
  <center>
    <%= will_paginate @issues, :class=> "pagination pagination-sm", renderer: BootstrapPagination::Rails %>
  </center>
<% end %>

app/views/issues/new.html.erb
<div class="page-header">
  <%= link_to magazine_issues_path(@magazine), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New issue</h1>
</div>
<%= render 'form' %>

app/views/issues/show.html.erb
<div class="page-header">
  <%= link_to magazine_issues_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_magazine_issue_path(@magazine, @issue), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show issue</h1>
</div>

<dl class="dl-horizontal">
  <dt>Magazine:</dt>
  <dd><%= @magazine.title %></dd>

  <dt>Number:</dt>
  <dd><%= @issue.number %></dd>

  <dt>Date:</dt>
  <dd><%= @issue.date %></dd>

  <dt>Due date:</dt>
  <dd><%= @issue.due_date %></dd>
</dl>