config/routes.rb
MagSys::Application.routes.draw do
  root 'main#index'
  get 'admin' , :to => "access#index"

  resources :main

  resources :orders 

  resources :contracts do
      collection do
      put :add
    end
  end

  resources :messages, :except => [:edit]

  resources :invoices

  resources :payments, :only => [:show, :index, :new, :create, :destroy]

  resources :users do
        collection do
        put :add
      end
  end

  resources :agencies

  resources :clients

  resources :magazines do
    resources :issues do 
      resources :fields do
        
      end

    end
  end

match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/magazine.rb
class Magazine < ActiveRecord::Base

	has_many :issues, :dependent => :destroy
	has_many :fields, :dependent => :destroy
	simple_roles

  mount_uploader :picture, PictureUploader

  	validates :title, :presence => true,
  					  :length => { :within => 1..255 }
  	validates :issue, :presence => true,
    					  :inclusion => { :in => 1..365, :message => " has to be between 1 and 365"}
  	validates :prints, 
  					       :inclusion => { :in => 1..999999, :message => " has to be between 1 and 999999"}
  	validates :subscribers, 
  					  :inclusion => { :in => 1..999999, :message => " has to be between 1 and 999999"}
  	validates :readership, 
  					  :inclusion => { :in => 1..999999, :message => " has to be between 1 and 999999"}				  				       

  	validates :status, :presence => true,
  					   :inclusion => { :in =>  %w(Y N) }
	
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :confirm_logged_in
  before_action :is_power_login, except: [:index]
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]
  
  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.where( :status => 'Y').order(:title).paginate(:page => params[:page], :per_page => 10)

    if session[:user_id]
      @user = User.find(session[:user_id])
      if is_power
        render :index
      else
        redirect_to main_index_path
      end
    else
      redirect_to main_index_path
    end
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render action: 'show', status: :created, location: @magazine }
      else
        format.html { render action: 'new' }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1
  # PATCH/PUT /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    
    @issues = Issue.where(:magazine_id => @magazine.id)    
    @fields = Field.where(:magazine_id => @magazine.id)

    @fields.update_all(:status =>'N')
    @issues.update_all(:status => 'N')
    @magazine.update_attribute(:status, 'N')
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: 'Magazine was successfully deleted.'  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magazine_params
      params.require(:magazine).permit(:title, :issue, :prints, :subscribers, :readership, :picture, :status)
    end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/magazines/_form.html.erb
<%= form_for(@magazine, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @magazine.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@magazine.errors.count, "error") %> prohibited this magazine from being saved:</h4>

      <ul>
      <% @magazine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :status, :class => "hidden form-control", :value => 'Y' %>

  <div class="form-group">
    <%= f.label :title, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :issue, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :issue, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :prints, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :prints, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :subscribers, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :subscribers, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :readership, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :readership, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :picture, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<div class="page-header">
  <%= link_to magazines_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @magazine, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing magazine</h1>
</div>

<%= render 'form' %>

app/views/magazines/index.html.erb
<div class="page-header">
  <%= link_to new_magazine_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Magazine
  <% end %>
  <%= link_to admin_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Admin CP
  <% end %>
  <h1>Listing magazines</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Issue</th>
            <th>Prints</th>
            <th>Subscribers</th>
            <th>Readership</th>
            <th>Picture</th>

      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @magazines) do |magazine| %>
            <td><%= magazine.title %></td>
            <td><%= magazine.issue %></td>
            <td><%= magazine.prints %></td>
            <td><%= magazine.subscribers %></td>
            <td><%= magazine.readership %></td>
            <td class ='text-center'><%= image_tag magazine.picture, size: "80x100" %></td>
            
            <td class ='text-center'><%= link_to 'Magazine issues', magazine_issues_path(magazine.id) %></td>
        <td class ='text-center'><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
        <td class ='text-center'><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
  <center>
  <%= will_paginate @magazines, :class=> "pagination pagination-sm", renderer: BootstrapPagination::Rails %>
  </center>
</div>

app/views/magazines/new.html.erb
<div class="page-header">
  <%= link_to magazines_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New magazine</h1>
</div>

<%= render 'form' %>

app/views/magazines/show.html.erb
<div class="page-header">
  <%= link_to magazines_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_magazine_path(@magazine), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%= @magazine.title %> magazine</h1>
</div>

<%= image_tag @magazine.picture, :class => 'col-md-3' %>

<dl class="dl-horizontal col-md-1">
  <dt>Issues:</dt>
  <dd><%= @magazine.issue %></dd>

  <dt>Prints:</dt>
  <dd><%= @magazine.prints %></dd>

  <dt>Subscribers:</dt>
  <dd><%= @magazine.subscribers %></dd>

  <dt>Readership:</dt>
  <dd><%= @magazine.readership %></dd>
</dl>