config/routes.rb
MagSys::Application.routes.draw do
  root 'main#index'
  get 'admin' , :to => "access#index"

  resources :main

  resources :orders 

  resources :contracts do
      collection do
      put :add
    end
  end

  resources :messages, :except => [:edit]

  resources :invoices

  resources :payments, :only => [:show, :index, :new, :create, :destroy]

  resources :users do
        collection do
        put :add
      end
  end

  resources :agencies

  resources :clients

  resources :magazines do
    resources :issues do 
      resources :fields do
        
      end

    end
  end

match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/field.rb
class Field < ActiveRecord::Base

	belongs_to :magazine
	has_many :orders
	simple_roles

	validates :title, :presence => true,
  					  :length => { :within => 1..255 }
  	validates :magazine_id, :presence => true,
  					        numericality: true
  	validates :height, 	numericality: true,
  						:presence => true,
  						:inclusion => { :in => 1..300, :message => " has to be between 1 and 300"}
  	validates :width, :presence => true,
  						numericality: true,
  						:inclusion => { :in => 1..450, :message => " has to be between 1 and 450"}				
  	validates :price, :presence => true,
  					  numericality: true	
	
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController

  before_action :confirm_logged_in, except: [ :index]
  before_action :is_power_login, except: [ :index, :index_other]
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  
  before_action :find_magazine
  before_action :find_issue
  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.where(:status => 'Y').where(:magazine_id => params[:magazine_id]).order(:height, :width).paginate(:page => params[:page], :per_page => 10)
    @order = Order.new
    if session[:user_id]
      @user = User.find(session[:user_id])
      if is_power
        render :index
      else
        render :index_other
      end
    else
      render :index_other
    end
  end

  def index_other
    @fields = Field.where(:status => 'Y').where(:magazine_id => params[:magazine_id]).order(:height, :width).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to [@magazine,@issue, @field], notice: 'Field was successfully created.' }
        format.json { render action: 'show', status: :created, location: @field }
      else
        format.html { render action: 'new' }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to [@magazine,@issue, @field], notice: 'Field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.update_attribute(:status, 'N')
    respond_to do |format|
      format.html { redirect_to magazine_issue_fields_path , notice: 'Field was successfully deleted.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:title, :height, :width, :price, :magazine_id, :status)
    end

    def find_magazine
      @magazine = Magazine.find(params[:magazine_id])
    end

    def find_issue
      @issue = Issue.find(params[:issue_id])
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_for([@magazine, @issue, @field], :html => { :class => "form-horizontal" }) do |f| %>
  <% if @field.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h4>

      <ul>
      <% @field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :status, :class => "hidden form-control", :value => 'Y' %>

  <div class="form-group">
    <%= f.label :title, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>

  <%= f.number_field :magazine_id, :class => "hidden form-control", :value => @magazine.id %>

  <div class="form-group">
    <%= f.label :height, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :height, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :width, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :width, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :price, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/fields/edit.html.erb
<div class="page-header">
  <%= link_to magazine_issue_fields_path(@magazine, @issue), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to magazine_issue_field_path(@magazine, @issue, @field), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing field</h1>
</div>

<%= render 'form' %>

app/views/fields/index.html.erb
<div class="page-header">
  <%= link_to magazines_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Show Magazines
  <% end %>
  <%= link_to new_magazine_issue_field_path(@magazine, @issue), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Field
  <% end %>
  <h1>Listing fields</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Height</th>
            <th>Width</th>
            <th>Price</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @fields) do |field| %>
            <td><%= field.title %></td>
            <td><%= field.height %></td>
            <td><%= field.width %></td>
            <td><%= field.price %></td>
        <td><%= link_to 'Edit', edit_magazine_issue_field_path(@magazine, @issue, field) %></td>
        <td><%= link_to 'Destroy', magazine_issue_field_path(@magazine, @issue, field), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
  <center>
  <%= will_paginate @fields, :class=> "pagination pagination-sm", renderer: BootstrapPagination::Rails %>
  </center>
</div>

app/views/fields/index_other.html.erb
<div class="page-header">
  <%= link_to magazine_issues_path(@magazine), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    <%= @magazine.title %> Issues
  <% end %>
  <h1>Available fields</h1>
</div>

<% if @fields.nil? || @fields.empty? %>
  <h3> No existing fields </h3>        
<% else %>
  <div class="row">
  <%= content_tag_for(:tr, @fields) do |field| %>
      <div class="col-md-3 col-sm-6 ">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= field.title %></h3>
                <p><b>Height: </b><%= field.height %> cm</p>
                <p><b>Width: </b><%= field.width %> cm</p>
                <p><b>Price: <%= number_with_precision(field.price, :precision => 2) %> EUR</b></p>
                

                  <%= form_for(@order, controller: 'orders', action: 'create', :html => { :class => "form-horizontal" }) do |f| %>
                    <% if @order.errors.any? %>
                      <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

                        <ul>
                        <% @order.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                        <%= f.number_field :issue_id, :class => "hidden form-control", :value => @issue.id %>                    
                        <%= f.number_field :field_id, :class => "hidden form-control", :value => field.id %>
                        <%= f.number_field :user_id, :class => "hidden form-control", :value => session[:user_id] %>          
                        <%= f.text_field :total_amount, :class => "hidden form-control", :value => field.price %>                  
                        <%= f.text_field :remaining, :class => "hidden form-control", :value => field.price %>                    
                        <%= f.text_field :special, :class => "hidden form-control", :value => '1' %>
                        <%= f.text_field :status, :class => "hidden form-control", :value => 'P' %> 
                                 
                    <center><%= f.submit "Add to Cart", :class => "show btn btn-primary "  %></center>
                  <% end %>                
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <center>
    <%= will_paginate @fields, :class=> "pagination pagination-sm", renderer: BootstrapPagination::Rails %>
  </center>
<% end %>

app/views/fields/new.html.erb
<div class="page-header">
  <%= link_to magazine_issue_fields_path(@magazine, @issue), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New field</h1>
</div>

<%= render 'form' %>

app/views/fields/show.html.erb
<div class="page-header">
  <%= link_to magazine_issue_fields_path(@magazine, @issue), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_magazine_issue_field_path(@magazine, @issue, @field), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show field</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @field.title %></dd>

  <dt>Height:</dt>
  <dd><%= @field.height %></dd>

  <dt>Width:</dt>
  <dd><%= @field.width %></dd>

  <dt>Price:</dt>
  <dd><%= @field.price %></dd>

</dl>